"""Idempotent, non-destructive setup of the instructions shared by both agents."""
from pathlib import Path
import os
import json
import shlex
import base64
import sys


def instructions(root):
    root = Path(root)
    source, target = root / 'CLAUDE.md', root / 'AGENTS.md'
    if not source.is_file():
        return
    if target.is_symlink():
        if os.readlink(target) == 'CLAUDE.md':
            return
        target.unlink()
    elif target.exists():
        print(f'warning: keeping existing {target}; expected a symlink to CLAUDE.md', file=sys.stderr)
        return
    try:
        target.symlink_to('CLAUDE.md')
    except OSError as e:
        raise RuntimeError(f'Cannot create {target}: {e}. On Windows enable Developer Mode for symlinks.') from e


GENERATED = '# Generated by just init; rerun after moving the checkout.\n'


def codex(root):
    root = Path(root).resolve()
    skills = root / '.agents/skills'
    source = root / '.claude/skills'
    if source.is_dir():
        # Git with core.symlinks=false checks out the link target as plain text.
        if skills.is_file() and not skills.is_symlink() and skills.read_text(encoding='utf-8').strip() == '../.claude/skills':
            skills.unlink()
        if not skills.exists() and not skills.is_symlink():
            skills.parent.mkdir(parents=True, exist_ok=True)
            try:
                skills.symlink_to('../.claude/skills', target_is_directory=True)
            except OSError as e:
                raise RuntimeError('Enable Windows Developer Mode to link .agents/skills, then rerun just init.') from e
    template = root / '.codex/config.template.toml'
    if not template.is_file():
        return
    target = root / '.codex/config.toml'
    if target.exists() and not target.read_text(encoding='utf-8').startswith(GENERATED):
        print(f'warning: keeping user-owned {target}; compare with config.template.toml', file=sys.stderr)
        return
    hook = str(root / 'scripts/codex_hook.py')
    # Encoded PowerShell avoids cmd/PowerShell quoting differences for spaces,
    # apostrophes and non-ASCII installation paths. The child inherits hook stdin.
    ps_quote = lambda value: "'" + value.replace("'", "''") + "'"
    ps = '& ' + ps_quote(sys.executable) + ' -X utf8 ' + ps_quote(hook) + '; exit $LASTEXITCODE'
    windows = 'powershell.exe -NoProfile -NonInteractive -EncodedCommand ' + base64.b64encode(ps.encode('utf-16-le')).decode('ascii')
    values = {'PYTHON': sys.executable, 'TOOLS': str(root / 'scripts/agent_tools.py'),
              'HOOK': shlex.join([sys.executable, '-X', 'utf8', hook]), 'WINDOWS_HOOK': windows,
              'DOCMAP': str(root / '.codex/agents/bcp-docmap.toml'),
              'PRECHECK': str(root / '.codex/agents/bcp-precheck.toml')}
    text = template.read_text(encoding='utf-8')
    for key, value in values.items():
        text = text.replace('@' + key + '@', json.dumps(value))
    target.write_text(GENERATED + text, encoding='utf-8')
