set(SOURCES
src/input/Keyboard.cpp
src/input/KeyState.cpp
src/input/Mouse.cpp
src/main.cpp
src/util/logger.cpp
src/window/Window.cpp
include/input/Keyboard.h
include/input/KeyState.h
include/input/Mouse.h
include/PCH.h
include/util/logger.h
include/window/BerniniWin.h
include/window/Window.h
)
