#pragma once

#include <bgl_common/idl/BoneSample.h>
#include <bgl_common/idl/Clip.h>
#include <bgl_common/idl/Constants.h>
#include <bgl_common/idl/CullStats.h>
#include <bgl_common/idl/CullView.h>
#include <bgl_common/idl/DebugRecord.h>
#include <bgl_common/idl/Entry.h>
#include <bgl_common/idl/InstanceVisibility.h>
#include <bgl_common/idl/LoosePbrMaterial.h>
#include <bgl_common/idl/MeshInstance.h>
#include <bgl_common/idl/Meshlet.h>
#include <bgl_common/idl/PbrMaterial.h>
#include <bgl_common/idl/PlaybackType.h>
#include <bgl_common/idl/PsoType.h>
#include <bgl_common/idl/Range.h>
#include <bgl_common/idl/RangeWithCount.h>
#include <bgl_common/idl/RawEntry.h>
#include <bgl_common/idl/RawRange.h>
#include <bgl_common/idl/RawTextureHandle.h>
#include <bgl_common/idl/RecordHeader.h>
#include <bgl_common/idl/Rig.h>
#include <bgl_common/idl/SkinnedBone.h>
#include <bgl_common/idl/SkinnedState.h>
#include <bgl_common/idl/SkinnedTableState.h>
#include <bgl_common/idl/Submesh.h>
#include <bgl_common/idl/VertexLayout.h>
